### PR TITLE
Support for axlsx  v3

### PR DESCRIPTION
**Pull request by davefp**
* Allow axlsx 3 as dependency
* Add appraisal gem to test multiple axlsx versions
* Use assert_nil rather than assert_equal nil in tests (latter is deprecated)

### CODE REVIEW

**Comment by davefp** [comment]
I've also added TravisCI config so that the tests will run on every push

**Comment by sakovias** [comment]
@davefp could you bump up the version, so we can release?

**Comment by davefp** [comment]
@sakovias done! 😃

**Comment by davefp** [comment]
@sakovias also you may need/want to sign in on travis-ci.org to turn on CI for this repo.

**Pull request merged**
