### PR TITLE
add multiple styles method on axlsx worksheet

### PR DESCRIPTION
**Pull request by johnkeith**
Hi this is a fantastic gem! Just wanted to add something I found myself needing today - the ability to add a bunch of styles to a cell or range at once. Let me know if you think this is the right way to go about that.

### CODE REVIEW

**Comment by sakovias** [comment]
Thanks for your feedback -- this looks good to me. Could you describe your motivation? I guess you'd like to make readable names for the styles you apply. E.g. this should work in the gem as is:

```ruby

add_style 'B2:F8', b: true, sz: 30
```

But the following wouldn't (which you need to have readable style names):

```ruby
add_style 'B2:F8', { b: true }, { sz: 30 }

```

As an option, we can update `add_style` method to handle both cases to keep API clean. Any thoughts?

**Comment by johnkeith** [comment]
Yes, totally agree on the API side of things. My goal here was to be able to define my styles once, with readable names like you said, then apply as needed to certain cells. (I've got a beast of a sheet I need to build out with tons of borders, alternating colors in the rows, different text colors, etc.).
```
@bold = { b: true }
@text_center = { alignment: { horizontal: :center } }
@blue_text = { fg_color: '009ec3' }
```
This way, you can simply define the styles and add them to each cell depending on what you need.
```
s.add_style "A5:D5", @background_grey, @blue_text, @border_top
```
Take a look at the revised add_style and let me know what you think. Seems to be working from my testing.

**Comment by sakovias** [comment]
Thanks for updating the code -- it works just fine. It's great you've got large test cases as this should allow us to polish the gem.

Please let me know if you're okay with the updated master branch. I will make a push to RubyGems if everything works fine for you.

**Comment by johnkeith** [comment]
@sakovias everything seems to be going great pulling from master! I'd say push it on out :)

**Comment by sakovias** [comment]
@johnkeith thanks for contributing! I've made a new release and pushed it to RubyGems.

**Pull request merged**
